version: '3.7'

services:

  postgres:
    image: postgres:latest
    hostname: postgres
    environment:
      POSTGRES_DB: example_database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  collector:
    image: otel/opentelemetry-collector-contrib:latest
    volumes:
    - ./otel-collector-config.yaml:/otel-collector-config.yaml
    entrypoint: ["/otelcontribcol"]
    command: ["--config", "/otel-collector-config.yaml"]
    environment:
      LOG_EXPORTER_LOG_LEVEL: "DEBUG"
    ports:
      - "4317:4317"   # grpc
      - "13133:13133" # health
