extensions:
  health_check: {}
receivers:
  otlp:
    protocols:
      grpc:
exporters:
  logging:
    logLevel: info
  newrelic:
    apikey: <API KEY>
  otlphttp:
    traces_endpoint: https://ingest.lightstep.com:443/traces/otlp/v0.6
    headers: "lightstep-access-token": "<LS_ACCESS_TOKEN>"
    compression: gzip
service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging, newrelic, datadog]
