extensions:
  health_check: {}
receivers:
  otlp:
    protocols:
      grpc:
exporters:
  logging:
    logLevel: info
  newrelic:
    apikey: <API KEY>
  datadog:
    api:
      key: <API KEY>
service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging, newrelic, datadog]
